# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74396b2a8fe8c9b996085bdf31c4830e619496eccc0af2788a4e886c28698160909b08a9013d3174931da5b8e8b1a0c71563d689e20e07a7d89ee8bd42b9cc24

test:
  secret_key_base: e2391a3f9a67c43b531ba6cde17328dc224125a296c1f6bd9989648064dfb8629387946d839575adf67a50d5c6733b204f7ee5c6c3f9def07e1df2ebcf4f2588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
